import{useEffect,useState}from'react';import{ArrowRight,BookOpen,Check,ExternalLink,FileDiff,RefreshCw,Scale,ShieldCheck,Wallet}from'lucide-react';import type{CalldataEncodable}from'genlayer-js/types';import{CONTRACT,configured,connectWallet,explorer,readFinalized,short,txUrl,writeFinalized}from'./genlayer';
type Log={label:string;hash:string};
const fixture={proposed:'2023-00414',final:'2024-09171',question:'Did the final rule materially change the proposed ban on worker non-compete clauses?'};
export default function App(){
 const[account,setAccount]=useState('');const[protocol,setProtocol]=useState<any>(null);const[totals,setTotals]=useState<any>(null);const[snapshot,setSnapshot]=useState<any>(null);const[job,setJob]=useState<any>(null);const[snapshotId,setSnapshotId]=useState('1');const[jobId,setJobId]=useState('1');const[predecessor,setPredecessor]=useState('0');const[busy,setBusy]=useState('');const[error,setError]=useState('');const[logs,setLogs]=useState<Log[]>([]);
 const read=async(fn:string,args:CalldataEncodable[]=[])=>readFinalized<any>(fn,args);
 const sync=async()=>{if(!configured)return;setError('');try{const p=await read('get_protocol'),t=await read('get_totals'),s=Number(snapshotId)>0?await read('get_snapshot',[Number(snapshotId)]):null,j=Number(jobId)>0?await read('get_job',[Number(jobId)]):null;setProtocol(p);setTotals(t);setSnapshot(s);setJob(j)}catch(e){setError(e instanceof Error?e.message:String(e))}};
 useEffect(()=>{void sync()},[]);
 const connect=async()=>{setError('');try{setAccount(await connectWallet())}catch(e){setError(e instanceof Error?e.message:String(e))}};
 const send=async(label:string,fn:string,args:CalldataEncodable[])=>{setBusy(label);setError('');try{if(!account)throw Error('Connect and verify a wallet before signing.');const hash=await writeFinalized(account,fn,args);setLogs(v=>[{label,hash},...v]);await sync()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}};
 const anchor=()=>send('Anchor source snapshot','anchor_source_pair',[fixture.proposed,fixture.final]);const create=()=>send('Create comparison','create_comparison',[Number(snapshotId),fixture.question,Number(predecessor)]);const assess=()=>send('Assess comparison','assess_comparison',[Number(jobId)]);
 return <><header><a className="brand" href="#top"><img src="/ruledelta-logo.png"/><span>RuleDelta<small>Federal Register scoped comparisons</small></span></a><div className="network"><i/>Studio Next 61997</div><button className="outline" onClick={connect}><Wallet size={16}/>{account?short(account):'Connect wallet'}</button></header>
 <main id="top"><section className="hero"><div className="heroCopy"><p className="eyebrow">PROPOSED RULE → FINAL RULE</p><h1>Know what changed.<br/><em>Prove what survived.</em></h1><p>RuleDelta verifies authoritative Federal Register identities and publishes a consensus-backed comparison certificate scoped to official API metadata and abstracts.</p><a className="primary" href="#workbench">Open comparison workbench <ArrowRight size={18}/></a></div><div className="visual"><img src="/ruledelta-logo.png"/><span>FTC · RIN 3084-AB74</span></div></section>
 <section className="metrics"><div><b>{totals?.snapshots||0}</b><span>Source snapshots</span></div><div><b>{totals?.jobs||0}</b><span>Comparison jobs</span></div><div><b>{totals?.certified||0}</b><span>Certificates</span></div><div><b>{protocol?.version||2}</b><span>Protocol version</span></div></section>
 <section className="principles"><div><p className="eyebrow">WHY RULEDELTA</p><h2>Identity first.<br/>Interpretation second.</h2></div><div className="principleGrid"><article><BookOpen/><h3>Public source</h3><p>No API key and no user-provided URL. Document identity comes from the Federal Register API.</p></article><article><ShieldCheck/><h3>Deterministic gate</h3><p>Type, agency, RIN, chronology and official GovInfo PDF identity must agree before AI runs.</p></article><article><Scale/><h3>Fail closed</h3><p>Schema errors, contradictions, source failures or validator conflicts produce UNRESOLVED.</p></article></div></section>
 <section id="workbench" className="workbench"><div className="workHead"><div><p className="eyebrow">LIVE COMPARISON WORKBENCH</p><h2>Build a scoped comparison certificate</h2></div><button className="outline" onClick={sync}><RefreshCw size={16}/>Sync</button></div><div className="notice">Scope: official Federal Register API identity fields, metadata and abstracts. This is not a full-text legal redline or legal advice.</div>{!configured&&<div className="notice">Deployment pending. The UI is ready; add VITE_CONTRACT_ADDRESS after the main wallet deploys the reviewed contract.</div>}{error&&<div className="error">{error}</div>}
 <div className="compare"><div className="document proposed"><span>PROPOSED RULE</span><b>{fixture.proposed}</b><small>January 19, 2023</small></div><FileDiff/><div className="document final"><span>FINAL RULE</span><b>{fixture.final}</b><small>May 7, 2024</small></div></div><div className="question"><span>LOCKED QUESTION</span><p>{fixture.question}</p></div>
 <div className="consoleGrid"><div className="actions"><button className="primary" disabled={!configured||!!busy} onClick={anchor}>{busy==='Anchor source snapshot'?'Validators anchoring...':'1 · Anchor source snapshot'}</button><div className="divider"/><label>Source snapshot ID<input value={snapshotId} onChange={e=>setSnapshotId(e.target.value)}/></label><label>Predecessor certificate ID<input value={predecessor} onChange={e=>setPredecessor(e.target.value)}/></label><button className="primary" disabled={!configured||!!busy} onClick={create}>{busy==='Create comparison'?'Submitting...':'2 · Create comparison job'}</button><div className="divider"/><label>Job ID<input value={jobId} onChange={e=>setJobId(e.target.value)}/></label><button className="dark" disabled={!configured||!!busy} onClick={assess}>{busy==='Assess comparison'?'Validators working...':'3 · Assess as independent wallet'}</button></div>
 <div className="certificate"><div className="certTitle"><Check/><span>METADATA / ABSTRACT CERTIFICATE</span></div><dl><dt>Contract</dt><dd>{short(CONTRACT)}</dd><dt>Scope</dt><dd>Federal Register API metadata + abstract</dd><dt>Snapshot</dt><dd>{snapshot?.id?`#${snapshot.id} · revision ${snapshot.revision}`:'—'}</dd><dt>Source pair</dt><dd>{short(snapshot?.pair_digest||'')}</dd><dt>Creator</dt><dd>{short(job?.creator||'')}</dd><dt>Assessor</dt><dd>{short(job?.assessor||'')}</dd><dt>Status</dt><dd>{job?.status||'Not loaded'}</dd><dt>Outcome</dt><dd>{job?.outcome||'—'}</dd><dt>Reason</dt><dd>{job?.reason||'—'}</dd><dt>Certificate</dt><dd>{short(job?.certificate_digest||'')}</dd></dl><div className="logs">{logs.map(x=><a key={x.hash} href={txUrl(x.hash)} target="_blank"><span>{x.label}</span><code>{short(x.hash)}</code><ExternalLink size={13}/></a>)}</div></div></div></section>
 </main><footer><b>RuleDelta</b><span>Public metadata/abstract evidence. Independent assessment. No custody.</span>{explorer&&<a href={explorer} target="_blank">View contract <ExternalLink size={14}/></a>}</footer></>}
