#!/usr/bin/env node
import{readFile,readdir}from"node:fs/promises";import{extname,join,relative}from"node:path";import{blake3}from"@noble/hashes/blake3.js";import{bytesToHex}from"@noble/hashes/utils.js";
const ROOT=join(process.cwd(),"frontend","dist"),PROJECT="ruledelta",API="https://api.cloudflare.com/client/v4";
function hidden(prompt){return new Promise((resolve,reject)=>{process.stdout.write(prompt);process.stdin.setRawMode(true);process.stdin.resume();process.stdin.setEncoding("utf8");let value="";const done=()=>{process.stdin.off("data",onData);process.stdin.setRawMode(false);process.stdin.pause()};const onData=chunk=>{for(const ch of chunk){if(ch==="\u0003"){done();reject(Error("Interrupted"));return}if(ch==="\r"||ch==="\n"){done();process.stdout.write("\n");resolve(value.trim());return}if(ch==="\u007f"||ch==="\b")value=value.slice(0,-1);else value+=ch}};process.stdin.on("data",onData)})}
async function walk(dir){let out=[];for(const e of await readdir(dir,{withFileTypes:true})){const p=join(dir,e.name);out=e.isDirectory()?out.concat(await walk(p)):out.concat(p)}return out}
const mime={".html":"text/html;charset=utf-8",".css":"text/css;charset=utf-8",".js":"application/javascript;charset=utf-8",".json":"application/json;charset=utf-8",".png":"image/png",".svg":"image/svg+xml",".ico":"image/x-icon",".txt":"text/plain;charset=utf-8",".map":"application/json;charset=utf-8"};
async function json(url,options={}){const res=await fetch(url,options);const text=await res.text();let body;try{body=JSON.parse(text)}catch{throw Error(`${res.status} ${url}: ${text.slice(0,300)}`)}if(!res.ok||body.success===false)throw Error(`${res.status} ${url}: ${JSON.stringify(body.errors||body)}`);return body.result}
const token=await hidden("Cloudflare API token: ");const auth={Authorization:`Bearer ${token}`};
const accounts=await json(`${API}/accounts?per_page=50`,{headers:auth});if(!accounts.length)throw Error("No Cloudflare account is visible to this token");const account=accounts[0].id;
let project;try{project=await json(`${API}/accounts/${account}/pages/projects/${PROJECT}`,{headers:auth})}catch(e){if(!String(e).includes("404"))throw e;project=await json(`${API}/accounts/${account}/pages/projects`,{method:"POST",headers:{...auth,"Content-Type":"application/json"},body:JSON.stringify({name:PROJECT,production_branch:"main"})})}
const files=[];const manifest={};for(const file of await walk(ROOT)){const bytes=await readFile(file),ext=extname(file).slice(1),base64=bytes.toString("base64"),hash=bytesToHex(blake3(new TextEncoder().encode(base64+ext))).slice(0,32),path="/"+relative(ROOT,file).replaceAll("\\","/");files.push({key:hash,value:base64,metadata:{contentType:mime[extname(file).toLowerCase()]||"application/octet-stream"},base64:true});manifest[path]=hash}
const upload=await json(`${API}/accounts/${account}/pages/projects/${PROJECT}/upload-token`,{headers:auth});const jwt={Authorization:`Bearer ${upload.jwt}`,"Content-Type":"application/json"};
const missing=await json(`${API}/pages/assets/check-missing`,{method:"POST",headers:jwt,body:JSON.stringify({hashes:files.map(x=>x.key)})});const missingSet=new Set(missing);const pending=files.filter(x=>missingSet.has(x.key));if(pending.length)await json(`${API}/pages/assets/upload`,{method:"POST",headers:jwt,body:JSON.stringify(pending)});await json(`${API}/pages/assets/upsert-hashes`,{method:"POST",headers:jwt,body:JSON.stringify({hashes:files.map(x=>x.key)})});
const form=new FormData();form.append("manifest",JSON.stringify(manifest));form.append("branch","main");form.append("commit_dirty","true");form.append("commit_message","Deploy verified RuleDelta v2 frontend");const deployment=await json(`${API}/accounts/${account}/pages/projects/${PROJECT}/deployments`,{method:"POST",headers:auth,body:form});
console.log(JSON.stringify({project:project.name||PROJECT,subdomain:project.subdomain,deploymentId:deployment.id,url:deployment.url,aliases:deployment.aliases,environment:deployment.environment,files:files.length,uploaded:pending.length},null,2));
